name:                waterfall-cad-examples
_version:            !include "../package-defaults.yaml"
version:             *version
github:              "joe-warren/opencascade-hs"
license:             LGPL-2.1
license-file:        LICENSE
author:              "Joe Warren"
maintainer:          "josephmarkwarren@gmail.com"
copyright:           "2023 Joe Warren"

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md

synopsis:            Examples for Waterfall CAD, a Declarative CAD/Solid Modeling Library
category:            Graphics
description:         Please see the README on GitHub at <https://github.com/joe-warren/opencascade-hs#readme>

dependencies:
- base >= 4.7 && < 5
- *opencascade-hs-bound
- *waterfall-cad-bound
- *waterfall-cad-svg-bound
- linear >= 1.21 && < 2
- lens >= 5 && < 6
- optparse-applicative >= 0.17 && < 0.19
- parsec >= 3.1 && < 3.2
- parser-combinators >= 1.2 && < 1.4
- xml >= 1 && <2 
- svg-tree >= 0.6 && < 1.0
- raw-strings-qq >= 1.1 && < 2

ghc-options: *ghc-options

executables:
  waterfall-cad-examples:
    main:                Main.hs
    dependencies: 
      waterfall-cad-examples
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  waterfall-cad-bench:
    main:                Main.hs
    dependencies: 
      - waterfall-cad-examples
      - criterion
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N



library:
  source-dirs: src
