name:                waterfall-cad
_version:            !include "../package-defaults.yaml"
version:             *version
github:              "joe-warren/opencascade-hs"
license:             LGPL-2.1
license-file:        LICENSE
author:              "Joe Warren"
maintainer:          "josephmarkwarren@gmail.com"
copyright:           "2023 Joe Warren"

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md

synopsis:            Declarative CAD/Solid Modeling Library
category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/joe-warren/opencascade-hs#readme>

dependencies:
- base >= 4.7 && < 5
- *opencascade-hs-bound
- linear >= 1.21 && < 2
- lens >= 5 && < 6
- lattices >= 2.0 && < 3
- resourcet >= 1.2 && < 1.4
- primitive >= 0.7 && < 0.10 

ghc-options: *ghc-options

library:
    source-dirs: src
