name:                opencascade-hs
_version:            !include "../package-defaults.yaml"
version:             *version
github:              "joe-warren/opencascade-hs"
license:             LGPL-2.1
author:              "Joe Warren"
maintainer:          "josephmarkwarren@gmail.com"
copyright:           "2023 Joe Warren"

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md
- cpp/*.h

include-dirs:
- cpp
- /usr/include/opencascade

extra-libraries:
- stdc++
- TKGeomBase 
- TKStd 
- TKG3d 
- TKG2d 
- TKMath 
- TKernel 
- TKBRep 
- TKGeomBase 
- TKOffset 
- TKFillet 
- TKBO 
- TKPrim 
- TKTopAlgo 
- TKSTL
- TKSTEP
- TKV3d 
- TKMesh
- TKRWMesh
- TKLCAF
- TKXCAF
- TKService
- TKShHealing

synopsis:            Thin Wrapper for the OpenCASCADE CAD Kernel
category:            Graphics,FFI

description:         Please see the README on GitHub at <https://github.com/joe-warren/opencascade-hs#readme>

dependencies:
- base >= 4.7 && < 5
- resourcet >= 1.2 && < 1.4

ghc-options: *ghc-options

cxx-options:
  - --std=c++17
  - -Wall
  - -Werror
  - -Wno-deprecated
  
library:
  source-dirs: src
  cxx-sources:
    - cpp/*.cpp