name:                opencascade-hs
_version:            !include "../package-defaults.yaml"
version:             *version
github:              "joe-warren/opencascade-hs"
license:             LGPL-2.1
author:              "Joe Warren"
maintainer:          "josephmarkwarren@gmail.com"
copyright:           "2023 Joe Warren"

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md
- cpp/*.h

include-dirs:
- cpp
- /usr/include/opencascade

extra-libraries:
- stdc++
- TKGeomBase 
- TKStd 
- TKG3d 
- TKG2d 
- TKHLR
- TKMath 
- TKernel 
- TKBRep 
- TKOffset 
- TKFillet 
- TKBO 
- TKPrim 
- TKTopAlgo 
- TKDESTL
- TKDESTEP
- TKDEGLTF
- TKDEOBJ
- TKV3d 
- TKMesh
- TKRWMesh
- TKLCAF
- TKXCAF
- TKService
- TKShHealing
- TKXSBase

synopsis:            Thin Wrapper for the OpenCASCADE CAD Kernel
category:            Graphics,FFI

description:         Please see the README on GitHub at <https://github.com/joe-warren/opencascade-hs#readme>

dependencies:
- base >= 4.7 && < 5
- resourcet >= 1.2 && < 1.4
- inline-c >= 0.9 && < 1.0
- inline-c-cpp >= 0.4 && < 0.6

ghc-options: *ghc-options

cxx-options:
  - --std=c++17
  - -Wall
  - -Werror
  - -Wno-deprecated
  
library:
  source-dirs: src
  cxx-sources:
    - cpp/*.cpp
  default-extensions:
    - QuasiQuotes
    - TemplateHaskell
    - OverloadedStrings