name:                opencascade-hs
version:             0.1.0.0
github:              "joe-warren/opencascade-hs"
license:             LGPL-2.1
author:              "Joe Warren"
maintainer:          "josephmarkwarren@gmail.com"
copyright:           "2023 Joe Warren"

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md

include-dirs:
- cpp
- /usr/include/opencascade

extra-libraries:
- stdc++
- TKGeomBase 
- TKStd 
- TKG3d 
- TKG2d 
- TKMath 
- TKernel 
- TKBRep 
- TKGeomBase 
- TKOffset 
- TKFillet 
- TKBO 
- TKPrim 
- TKTopAlgo 
- TKSTL
- TKSTEP
- TKV3d 
- TKMesh
- TKService

synopsis:            Thin Wrapper for the OpenCASCADE CAD Kernel
category:            Graphics,FFI

description:         Please see the README on GitHub at <https://github.com/joe-warren/opencascade-hs#readme>

dependencies:
- base >= 4.7 && < 5
- resourcet >= 1.2 && < 1.4
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

cc-options:
  - -Werror-implicit-function-declaration

cxx-options:
  - --std=c++17
  
library:
  source-dirs: src
  cxx-sources:
    - cpp/*.cpp
