name:                waterfall-cad-svg
_version:            !include "../package-defaults.yaml"
version:             *version
github:              "joe-warren/opencascade-hs"
license:             LGPL-2.1
license-file:        LICENSE
author:              "Joe Warren"
maintainer:          "josephmarkwarren@gmail.com"
copyright:           "2025 Joe Warren"

synopsis:            Declarative CAD/Solid Modeling Library, SVG Support 
category:            Graphics
description:         Please see the README on GitHub at <https://github.com/joe-warren/opencascade-hs#readme>

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- *waterfall-cad-bound
- *opencascade-hs-bound
- svg-tree >= 0.6 && < 1.0
- attoparsec >= 0.14 && < 1.0
- text >= 1.2 && < 3.0
- linear >= 1.0 && < 2.0 
- lens > 5 && < 6
- resourcet >= 1.2 && < 1.4
- JuicyPixels >= 3 && < 4

ghc-options: *ghc-options

library:
  source-dirs: src
